### ISSUE TITLE
Can't get data when the user play to many matches.

### ISSUE THREAD

**Issue by ChineseOuchie** [Lifeformwp/php-pubg#7]
`Fatal error: Maximum execution time of 30 seconds exceeded in \vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php on line 41`

Is there a way to extend the execution time?

**Comment by Lifeformwp** [comment]
Sure, see the PHP config here:

http://php.net/manual/en/function.set-time-limit.php
http://php.net/manual/en/info.configuration.php#ini.max-execution-time

**Comment by Lifeformwp** [comment]
Please reopen if you have some further questions about it
